spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
    hikari:
      minimum-idle: 15
      maximum-pool-size: 25

logging:
  level:
    root: INFO
    com.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG

kakao:
  token:

# AWS Setting
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key:
      secret-key:
    s3:
      bucket: core-image-bucket
      url: https://core-image-bucket.s3.ap-northeast-2.amazonaws.com
